# Generated by Django 3.1.4 on 2021-01-09 17:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriýanyň ady')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoriýa',
                'verbose_name_plural': 'Kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şäheriň ady')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='afisha.city')),
            ],
            options={
                'verbose_name': 'Şäher',
                'verbose_name_plural': 'Şäherler',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mahabatyň ady')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d', verbose_name='Surat')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagt')),
                ('stock', models.BooleanField(default=False, verbose_name='Aksiýa')),
                ('views', models.IntegerField(default=0, verbose_name='Görlenleriň sany')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='afisha.category', verbose_name='Kategoriýa')),
                ('city', mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='afisha.city', verbose_name='Şäher')),
            ],
            options={
                'verbose_name': 'Mahabat',
                'verbose_name_plural': 'Mahabatlar',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
