# Generated by Django 3.1.4 on 2021-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-sort_order'], 'verbose_name': 'Mahabat', 'verbose_name_plural': 'Mahabatlar'},
        ),
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon belgi'),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Jaň düwmesine basylanlaryň samy'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Görlenleriň sany'),
        ),
    ]
