# Generated by Django 3.1.4 on 2021-01-10 11:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', related_query_name='category', to='afisha.category', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', related_query_name='city', to='afisha.city', verbose_name='Şäher'),
        ),
    ]
