# Generated by Django 3.1.4 on 2021-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_auto_20210119_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sosial tordaky akkaundyň ady')),
                ('link', models.URLField(verbose_name='URL-y')),
            ],
            options={
                'verbose_name': 'Sosial tor',
                'verbose_name_plural': 'Sosial torlar',
            },
        ),
    ]
