# Generated by Django 3.1.4 on 2021-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_socialnetworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-sort_order'], 'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_tk',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='ad',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Blokdamy'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_tk',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_tk',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Postyň ady'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Postyň ady'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title_tk',
            field=models.CharField(max_length=200, null=True, verbose_name='Postyň ady'),
        ),
    ]
