# Generated by Django 3.1.4 on 2021-01-31 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0004_auto_20210131_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content_tk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
    ]
